### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Finsiii** [hasyim404/WA-Intip#2]
[!] [02/10/2024-21.36.04] Error:  TypeError: Cannot read properties of undefined (reading 'data')
    at intipMessage (/home/finsi/CODINGAN/wa-intip/index.js:177:65)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async processMessageQueue (/home/finsi/CODINGAN/wa-intip/index.js:108:15)
[!] [02/10/2024-21.36.19] Error:  TypeError: Cannot read properties of undefined (reading 'data')
    at intipMessage (/home/finsi/CODINGAN/wa-intip/index.js:177:65)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async processMessageQueue (/home/finsi/CODINGAN/wa-intip/index.js:108:15)
[!] [02/10/2024-21.36.32] undefined

**Comment by muhismail015** [comment]
trouble from library wwebjs, still waiting for fix

**Comment by muhismail015** [comment]
> [!] [02/10/2024-21.36.04] Error: TypeError: Cannot read properties of undefined (reading 'data') at intipMessage (/home/finsi/CODINGAN/wa-intip/index.js:177:65) at process.processTicksAndRejections (node:internal/process/task_queues:105:5) at async processMessageQueue (/home/finsi/CODINGAN/wa-intip/index.js:108:15) [!] [02/10/2024-21.36.19] Error: TypeError: Cannot read properties of undefined (reading 'data') at intipMessage (/home/finsi/CODINGAN/wa-intip/index.js:177:65) at process.processTicksAndRejections (node:internal/process/task_queues:105:5) at async processMessageQueue (/home/finsi/CODINGAN/wa-intip/index.js:108:15) [!] [02/10/2024-21.36.32] undefined

do this:
`npm install github:alechkos/whatsapp-web.js#downloadable-view-once-msgs`

or:
git pull the repo, and then npm install for update package
